export const SCHEDULER_FORM_RESET = "SCHEDULER_FORM_RESET";
export const SCHEDULER_FORM_START_LOADER = "SCHEDULER_FORM_START_LOADER";
export const SCHEDULER_FORM_DATA_SUCCESS = "SCHEDULER_FORM_DATA_SUCCESS";
export const SCHEDULER_FORM_DATA_FAILURE = "SCHEDULER_FORM_DATA_FAILURE";

export const GET_TEAMS_RESET = "GET_TEAMS_RESET";
export const GET_TEAMS_START_LOADER = "GET_TEAMS_START_LOADER";
export const GET_TEAMS_DATA_SUCCESS = "GET_TEAMS_DATA_SUCCESS";
export const GET_TEAMS_DATA_FAILURE = "GET_TEAMS_DATA_FAILURE";

export const SUBMIT_TEAMS_RESET = "SUBMIT_TEAMS_RESET";
export const SUBMIT_TEAMS_START_LOADER = "SUBMIT_TEAMS_START_LOADER";
export const TEAM_FORM_DATA_SUCCESS = "TEAM_FORM_DATA_SUCCESS";
export const TEAM_FORM_DATA_FAILURE = "TEAM_FORM_DATA_FAILURE";

export const GET_TOURNAMENTS_RESET = "GET_TOURNAMENTS_RESET";
export const GET_TOURNAMENTS_START_LOADER = "GET_TOURNAMENTS_START_LOADER";
export const GET_TOURNAMENTS_DATA_SUCCESS = "GET_TOURNAMENTS_DATA_SUCCESS";
export const GET_TOURNAMENTS_DATA_FAILURE = "GET_TOURNAMENTS_DATA_FAILURE";

export const GET_UNAPPROVED_TEAMS_RESET = "GET_UNAPPROVED_TEAMS_RESET";
export const GET_UNAPPROVED_TEAMS_START_LOADER =
    "GET_UNAPPROVED_TEAMS_START_LOADER";
export const GET_UNAPPROVED_TEAMS_DATA_SUCCESS =
    "GET_UNAPPROVED_TEAMS_DATA_SUCCESS";
export const GET_UNAPPROVED_TEAMS_DATA_FAILURE =
    "GET_UNAPPROVED_TEAMS_DATA_FAILURE";

export const APPROVE_TEAMS_RESET = "APPROVE_TEAMS_RESET";
export const START_APPROVE_TEAMS_LOADER = "START_APPROVE_TEAMS_LOADER";
export const TEAM_APPROVAL_SUCCESS = "TEAM_APPROVAL_SUCCESS";
export const TEAM_APPROVAL_FAILURE = "TEAM_APPROVAL_FAILURE";

export const REFEREE_FORM_DATA_SUCCESS = "REFEREE_FORM_DATA_SUCCESS";
export const REFEREE_FORM_DATA_FAILURE = "REFEREE_FORM_DATA_FAILURE";
export const SUBMIT_REFEREE_RESET = "SUBMIT_REFEREE_RESET";
export const SUBMIT_REFEREE_START_LOADER = "SUBMIT_REFEREE_START_LOADER";

export const GET_REFEREE_SCHEDULE_RESET = "GET_REFEREE_SCHEDULE_RESET";
export const GET_REFEREE_SCHEDULE_START_LOADER = "GET_REFEREE_SCHEDULE_START_LOADER";
export const GET_REFEREE_SCHEDULE_DATA_SUCCESS = "GET_REFEREE_SCHEDULE_DATA_SUCCESS";
export const GET_REFEREE_SCHEDULE_DATA_FAILURE = "GET_REFEREE_SCHEDULE_DATA_FAILURE";


export const GET_MATCHES_RESET = "GET_MATCHES_RESET";
export const GET_MATCHES_START_LOADER = "GET_MATCHES_START_LOADER";
export const GET_MATCHES_DATA_SUCCESS = "GET_MATCHES_DATA_SUCCESS";
export const GET_MATCHES_DATA_FAILURE = "GET_MATCHES_DATA_FAILURE";

export const GET_SELECTED_TOURNAMENT_RESET = "GET_SELECTED_TOURNAMENT_RESET";
export const GET_SELECTED_TOURNAMENT_START_LOADER = "GET_SELECTED_TOURNAMENT_START_LOADER";
export const GET_SELECTED_TOURNAMENT_DATA_SUCCESS = "GET_SELECTED_TOURNAMENT_DATA_SUCCESS";
export const GET_SELECTED_TOURNAMENT_DATA_FAILURE = "GET_SELECTED_TOURNAMENT_DATA_FAILURE";

export const UPDATE_MATCH_RESET = "UPDATE_MATCH_RESET";
export const START_UPDATE_MATCH_LOADER = "START_UPDATE_MATCH_LOADER";
export const MATCH_UPDATION_SUCCESS = "MATCH_UPDATION_SUCCESS";
export const MATCH_UPDATION_FAILURE = "MATCH_UPDATION_FAILURE";

export const GET_UNAPPROVED_REFEREE_RESET = "GET_UNAPPROVED_REFEREE_RESET";
export const GET_UNAPPROVED_REFEREE_DATA_SUCCESS = "GET_UNAPPROVED_REFEREE_DATA_SUCCESS";
export const GET_UNAPPROVED_REFEREE_DATA_FAILURE = "GET_UNAPPROVED_REFEREE_DATA_FAILURE";

export const APPROVE_REFEREE_RESET = "APPROVE_REFEREE_RESET";
export const REFEREE_APPROVAL_SUCCESS = "REFEREE_APPROVAL_SUCCESS";
export const REFEREE_APPROVAL_FAILURE = "REFEREE_APPROVAL_FAILURE";
